### ISSUE TITLE
Clava requires Xserver

### ISSUE THREAD

**Issue by ppietrasa** [specs-feup/clava#22]
It shouldn't be strictly necessary. I'm not running any GUI when transpiling. Perhaps the requirement could be dropped:

```
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
        at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:232)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:588)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:583)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582)
        at java.desktop/javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:661)
        at pt.up.fe.specs.util.SpecsSwing.getSystemLookAndFeel(Unknown Source)
        at pt.up.fe.specs.util.SpecsSwing.setSystemLookAndFeel(Unknown Source)
        at pt.up.fe.specs.util.SpecsSystem.programStandardInit(Unknown Source)
        at pt.up.fe.specs.clava.weaver.ClavaWeaverLauncher.main(Unknown Source)

```

**Comment by joaobispo** [comment]
I've pushed a [commit](https://github.com/specs-feup/specs-java-libs/commit/b307aa159d746d32a0eb59ba2c4a6d014ac48e51) in [specs-java-libs](https://github.com/specs-feup/specs-java-libs) that should fix this.

**Comment by ppietrasa** [comment]
It still doesn't work.
Looking at your [commit](https://github.com/specs-feup/specs-java-libs/commit/b307aa159d746d32a0eb59ba2c4a6d014ac48e51) it still reaches getSystemLookAndFeel() from setSystemLookAndFeel(). The stack trace did not change.

**Comment by joaobispo** [comment]
I was looking for a way to detect if there is an X Server running, but it seems there is no standard way. 

Please tell me what happens if you run the command `xdpyinfo`, and what is the exit code?

**Comment by ppietrasa** [comment]
Hi Joao,

This is what I get upon invoking xdpyinfo:

```
$ xdpyinfo
connect /tmp/.X11-unix/X0: No such file or directory
xdpyinfo:  unable to open display "localhost:10.0".

$ echo $?
1
```

**Comment by joaobispo** [comment]
I was planning on running that command and check the exit code in order to determine if it was headless or not, but [I've pushed an improved headless check](https://github.com/specs-feup/specs-java-libs/commit/1a5653d9f7e346991d1d3cb72daf09a196dca9b6) that is platform-independent.

Also, even if the check fails, it will no longer throw an exception but instead, show a warning message.

**Comment by ppietrasa** [comment]
I gave it a try again, but it still failed.

The trace now looks a bit different -  isHeadless() is called and eventually throws:
```
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
        at pt.up.fe.specs.util.SpecsSwing.isHeadless(Unknown Source)
        at pt.up.fe.specs.util.SpecsSwing.setSystemLookAndFeel(Unknown Source)
        at pt.up.fe.specs.util.SpecsSystem.programStandardInit(Unknown Source)
        at pt.up.fe.specs.clava.weaver.ClavaWeaverLauncher.main(Unknown Source)
```
One way to quickly test this (assuming linux host at hand) is to set the DISPLAY variable to a dummy value, e.g.:
```
$ DISPLAY=dummy:7.7 java -jar ../spu/java/native/ClavaWeaver.jar --help
```

**Comment by ppietrasa** [comment]
Ohh. I just realized that if I remove the default DISPLAY variable on my system then clava works.
I guess I could leave with that.

**Comment by joaobispo** [comment]
Well, I've changed isHeadless() to assume no display is available if any Exception is thrown, instead of just testing for HeadlessException.

**Comment by ppietrasa** [comment]
This is funny.

The problem is that, when DISPLAY is faulty then java.awt.AWTError is thrown which derives from java.lang.Error and not from java.lang.Exception:
```
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.
```

I like your original idea of testing for HeadlessException, but supplemented by testing for AWTException. This way we are not casting the net too wide.

**Comment by joaobispo** [comment]
Thanks for the insight, I've pushed a fix that tests again for HeadlessException, and now also AWTError. By the way, the HeadlessException was not my idea, it was from a Stackoverflow link (mentioned in the method documentation).

**Comment by ppietrasa** [comment]
This works fine now. Thanks!
Closing..
